version: '3.8'

services:

  laravel-api:
    build:
      context: ./laravel-api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
